services:
  clothcraft-app:
    image: clothcraft-app:latest
    hostname: clothcraft/app
    container_name: clothcraft-app
    restart: always
    volumes:
      - ./app:/app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@clothcraft-db:5432/clothcraft
    depends_on:
      clothcraft-db:
        condition: service_healthy
    networks:
      clothcraft-network:
        ipv4_address: 172.20.0.11

  clothcraft-db:
    image: postgres:latest
    hostname: clothcraft/db
    container_name: clothcraft-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clothcraft
      # ports:
      #   - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - ./db/init_updt:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      clothcraft-network:
        ipv4_address: 172.20.0.10

networks:
  clothcraft-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
